name: jupyter
channels:
 - conda-forge
dependencies:
# Python version is pinned to 3.13 in the official jupyter/minimal-notebook image
 - python=3.13
# Jupyter packages already in the jupyter/base-notebook image
 - jupyterhub-singleuser
 - jupyterlab
 - nbclassic
 - notebook>=7.2.2
# Additional Jupyter packages and extensions
 - jupyterlab-git  # git is already installed in the jupyter/minimal-notebook image
 - dask-labextension
# STAC
 - pystac
 - pystac-client